# Use Python 3.11 slim Buster as the base image
FROM python:3.11.0b4-slim-buster

# Copy all application files into the container
COPY . .

# Run the Python application when the container starts
CMD ["python", "./hello.py"]
